scen_channel:  0
marker_channel: 1
nuclei_channel: 2
x_pad: 50
y_pad: 50
raw_data_folder: 'raw_data'
classifications_folder: 'output/2D_class_new'
cl3D_filename: 'models/scen_3D.cl'
output_folder: 'output_script_test'